name: Weather App CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-weather-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install coverage

      - name: Create .env file
        run: |
          echo "OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" > venv/.env


      - name: Run unit tests
        run: |
          source venv/bin/activate
          pytest tests/test_get_weather_unit.py --cov=weather_app --cov-append

      - name: Run integration tests
        run: |
          source venv/bin/activate
          pytest tests/test_get_weather_integration.py --cov=weather_app --cov-append

      - name: Run translation tests
        run: |
          source venv/bin/activate
          pybabel compile -d locales
          pytest tests/test_translation_pt_pt.py --cov=weather_app --cov-append

      - name: Run chart API tests
        run: |
          source venv/bin/activate
          pytest tests/test_chart_api.py --cov=weather_app --cov-append
